### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by tudorcoroian17** [JurcanDiana/Mythical-Creatures-Mod#1]
Draw a Gantt Chart to showcase the initial project plan. It should contain:
- Tasks (what you plan to implement) -> features
- Time estimations (day-granularity)
- Timeline (in months) -> from October to May

**Comment by tudorcoroian17** [comment]
Please attach Gantt Chart to this issue and close it 😄

**Comment by JurcanDiana** [comment]
[GanttChart.xlsx](https://github.com/JurcanDiana/Mythical-Creatures-Mod/files/13673218/GanttChart.xlsx)
