### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by tudorcoroian17** [JurcanDiana/Mythical-Creatures-Mod#2]
Design the initial model of the application (mod). It should contain classes of new items that you plan to add (or items that instantiate the `Item` class), as well as blocks (and block entities, if applicable), entities, biomes. This should be (roughly) an UML diagram.
Additionally, feel free to draw other diagrams that you need, such as:
- use case diagrams
- system diagrams

**Comment by tudorcoroian17** [comment]
Please attach .ppt to this issue and close it 😄

**Comment by JurcanDiana** [comment]
[Uploading PresentationPrototype.pptx…]()
