### ISSUE TITLE
Unicorn Entity

### ISSUE THREAD

**Issue by tudorcoroian17** [JurcanDiana/Mythical-Creatures-Mod#3]
Design the Unicorn entity in BlockBench. Attach images with the entity to this issue.

Implement the Unicorn entity in game. Take note of algorithms used for movement, player interaction, wander (these are just a few examples). 

Come up with an algorithm (first pseudocode, then Java code) for the functionalities that you want your entity to have. State those functionalities (clearly) in this issue, as well as the pseudocode you plan to implement.

**Comment by JurcanDiana** [comment]
![unicorn1](https://github.com/JurcanDiana/Mythical-Creatures-Mod/assets/86732510/4dfdff81-3f19-4458-82c8-b294ac1c9f91)
![unicorn2](https://github.com/JurcanDiana/Mythical-Creatures-Mod/assets/86732510/0114eb9d-b647-4b1b-b1d7-d71de4b734c5)
![unicorn3](https://github.com/JurcanDiana/Mythical-Creatures-Mod/assets/86732510/71166d68-9a58-4a42-aa0c-64a16968393d)
![texture_unicorn](https://github.com/JurcanDiana/Mythical-Creatures-Mod/assets/86732510/e3c47635-c478-44fd-a54b-170e8a6e0e6b)

**Comment by JurcanDiana** [comment]
<img width="960" alt="image" src="https://github.com/JurcanDiana/Mythical-Creatures-Mod/assets/86732510/559621ac-a14f-479f-baf0-deba8aca50b3">
